### ISSUE TITLE
Cultured Code

### ISSUE THREAD

**Issue by phlippieb** [phlippieb/resume#10]
# Info

There are no current openings, but they welcome unsolicited submissions. See https://culturedcode.com/jobs/

# Tasks

- [x] Tailor CV
- [x] Review CV
- [x] Write cover letter
   - [x] Mention learning german?
- [x] Review cover letter
- [x] Create release
- [x] Send application
